xcopy \throttle\voice\vista.33\1008.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1009.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1010.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1011.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1012.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1013.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1014.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1015.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1017.voc \throttle\video\jumpgorg
xcopy \throttle\voice\vista.33\1016.voc \throttle\video\jumpgorg

